//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Object87Bot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keys
    {
        public long Id { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual BlueKey BlueKey { get; set; }
        public virtual GreenKey GreenKey { get; set; }
    }
}
