//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Object87Bot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Object87BotModelContainer : DbContext
    {
        public Object87BotModelContainer()
            : base("name=Object87BotModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Player> PlayerSet { get; set; }
        public virtual DbSet<Items> ItemsSet { get; set; }
        public virtual DbSet<Keys> KeysSet { get; set; }
        public virtual DbSet<Flashlight> FlashlightSet { get; set; }
        public virtual DbSet<BlueKey> BlueKeySet { get; set; }
        public virtual DbSet<GreenKey> GreenKeySet { get; set; }
    }
}
